[package]
name = "http-pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#actix-web = "1.0.8"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }